"""index detections by run

Revision ID: 716e20767c47
Revises: 84e855ff91d9
Create Date: 2026-08-22 23:38:40.641911
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '716e20767c47'
down_revision = '84e855ff91d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_detections_run', 'detections', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_detections_run', table_name='detections')
    # ### end Alembic commands ###
