"""initial schema

Revision ID: 81d007f7686b
Revises: 
Create Date: 2026-08-22 22:37:35.128103
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '81d007f7686b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=16), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('sha', sa.String(length=64), nullable=False),
    sa.Column('source_dataset', sa.String(length=255), nullable=False),
    sa.Column('dataset_version', sa.String(length=64), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('model_card_uri', sa.String(length=512), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promoted_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('stores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('chain', sa.String(length=128), nullable=False),
    sa.Column('store_format', sa.String(length=16), nullable=False),
    sa.Column('area_id', sa.String(length=64), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('photo_policy', sa.String(length=16), nullable=False),
    sa.Column('visit_window', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_code')
    )
    op.create_index('ix_stores_area', 'stores', ['area_id'], unique=False)
    op.create_index('ix_stores_geo', 'stores', ['lat', 'lng'], unique=False)
    op.create_table('sync_operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('area_id', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.Column('gps_match', sa.Boolean(), nullable=False),
    sa.Column('photo_consent_confirmed', sa.Boolean(), nullable=True),
    sa.Column('osa_before', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('osa_after', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_visits_store_time', 'visits', ['store_id', 'checked_in_at'], unique=False)
    op.create_table('captures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('shelf_bay_label', sa.String(length=64), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(length=8), nullable=False),
    sa.Column('face_blur_applied', sa.Boolean(), nullable=True),
    sa.Column('face_blur_count', sa.Integer(), nullable=True),
    sa.Column('retention_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('client_idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_idempotency_key')
    )
    op.create_index('ix_captures_visit', 'captures', ['visit_id'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('capture_id', sa.UUID(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=128), nullable=False),
    sa.Column('semantic_type', sa.String(length=16), nullable=False),
    sa.Column('bbox_x', sa.Float(), nullable=False),
    sa.Column('bbox_y', sa.Float(), nullable=False),
    sa.Column('bbox_w', sa.Float(), nullable=False),
    sa.Column('bbox_h', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('shelf_row_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['capture_id'], ['captures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_detections_capture', 'detections', ['capture_id'], unique=False)
    op.create_table('inference_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('capture_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inference_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['capture_id'], ['captures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_capture', 'inference_jobs', ['capture_id'], unique=False)
    op.create_table('shelf_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('capture_id', sa.UUID(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('total_shelf_area', sa.Float(), nullable=False),
    sa.Column('gap_area', sa.Float(), nullable=False),
    sa.Column('gap_ratio', sa.Float(), nullable=False),
    sa.Column('osa_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('low_confidence_count', sa.Integer(), nullable=False),
    sa.Column('config_version', sa.String(length=32), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['capture_id'], ['captures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analyses_capture', 'shelf_analyses', ['capture_id'], unique=False)
    op.create_table('gap_findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('capture_id', sa.UUID(), nullable=False),
    sa.Column('detection_id', sa.UUID(), nullable=False),
    sa.Column('shelf_row_index', sa.Integer(), nullable=False),
    sa.Column('position_label', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_low_confidence', sa.Boolean(), nullable=False),
    sa.Column('sku_code', sa.String(length=64), nullable=False),
    sa.Column('sku_name', sa.String(length=255), nullable=False),
    sa.Column('sku_brand', sa.String(length=128), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('facings', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.String(length=16), nullable=False),
    sa.Column('rejected_reason', sa.String(length=32), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['capture_id'], ['captures.id'], ),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_findings_capture', 'gap_findings', ['capture_id'], unique=False)
    op.create_index('ix_findings_pending', 'gap_findings', ['verification_status'], unique=False, postgresql_where=sa.text("verification_status = 'PENDING'"))
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('gap_finding_id', sa.UUID(), nullable=False),
    sa.Column('sku_code', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('blocked_reason', sa.String(length=32), nullable=True),
    sa.Column('after_capture_id', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['after_capture_id'], ['captures.id'], ),
    sa.ForeignKeyConstraint(['gap_finding_id'], ['gap_findings.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gap_finding_id', name='uq_task_per_finding')
    )
    op.create_index('ix_tasks_visit', 'tasks', ['visit_id'], unique=False)
    op.create_table('replenishment_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('sku_code', sa.String(length=64), nullable=False),
    sa.Column('source_task_id', sa.UUID(), nullable=True),
    sa.Column('quantity_hint', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replenishment_requests')
    op.drop_index('ix_tasks_visit', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_findings_pending', table_name='gap_findings', postgresql_where=sa.text("verification_status = 'PENDING'"))
    op.drop_index('ix_findings_capture', table_name='gap_findings')
    op.drop_table('gap_findings')
    op.drop_index('ix_analyses_capture', table_name='shelf_analyses')
    op.drop_table('shelf_analyses')
    op.drop_index('ix_jobs_capture', table_name='inference_jobs')
    op.drop_table('inference_jobs')
    op.drop_index('ix_detections_capture', table_name='detections')
    op.drop_table('detections')
    op.drop_index('ix_captures_visit', table_name='captures')
    op.drop_table('captures')
    op.drop_index('ix_visits_store_time', table_name='visits')
    op.drop_table('visits')
    op.drop_table('users')
    op.drop_table('sync_operations')
    op.drop_index('ix_stores_geo', table_name='stores')
    op.drop_index('ix_stores_area', table_name='stores')
    op.drop_table('stores')
    op.drop_table('model_versions')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
