"""Derive the demo planogram from the class map an artifact ships with.

The backend needs a name to put on a gap: "ชั้นที่ 2 · ตำแหน่งซ้าย" does not
tell a rep what to put back. In a real deployment that name comes from the
planogram system. There is no planogram system here, so this script builds a
stand-in out of the only ground truth available — the products the model was
actually trained to recognise.

Why this lives on the ML side: the class map is the model's own file, and the
raw class names in it are exactly what the backend is forbidden to read. This
script reads them once, at build time, and emits a plain SKU list. What the
backend loads has no class ids, no semantic types, and nothing to branch on —
it is a catalogue of products, which is what a planogram is.

`priority` and `facings` are measured, not invented. A product occupying four
facings on the average shelf it appears on really does need restocking before
one that occupies a single facing, and the label files are the only place that
number exists.

    python -m shelfeye_ml.artifact.export_planogram [ARTIFACT_DIR]
"""

from __future__ import annotations

import argparse
import collections
import json
import statistics
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_ARTIFACT = REPO_ROOT / "model" / "artifacts" / "shelf-product-yolo26l-960"
DATA_ROOT = REPO_ROOT / "model" / "data"
OUTPUT = REPO_ROOT / "backend" / "app" / "services" / "planogram.json"

# Every split, because the planogram describes the shelf, not the experiment.
# Holding `test` out matters when measuring a model; it would only make the
# facing counts noisier here.
SPLITS = ("train", "valid", "test")


def _product_classes(class_map_path: Path) -> dict[int, str]:
    raw = yaml.safe_load(class_map_path.read_text())
    return {
        int(cid): body["name"]
        for cid, body in raw["classes"].items()
        if body["semantic_type"] == "PRODUCT"
    }


def _occurrences_per_image() -> dict[int, list[int]]:
    """How many boxes of each class appear on each image that contains it."""
    counts: dict[int, list[int]] = collections.defaultdict(list)
    for split in SPLITS:
        for label_path in sorted((DATA_ROOT / split / "labels").glob("*.txt")):
            per_image = collections.Counter(
                int(line.split()[0]) for line in label_path.read_text().splitlines() if line.split()
            )
            for class_id, count in per_image.items():
                counts[class_id].append(count)
    return counts


def build(artifact_dir: Path) -> dict:
    class_map_path = artifact_dir / "class_map.yaml"
    if not class_map_path.exists():
        raise SystemExit(f"no class map at {class_map_path} — train or download an artifact first")
    if not (DATA_ROOT / "train" / "labels").is_dir():
        raise SystemExit(f"no dataset at {DATA_ROOT} — run `make dataset` first")

    products = _product_classes(class_map_path)
    occurrences = _occurrences_per_image()

    # Most-stocked first, so the lowest SKU codes are the products a demo is
    # most likely to actually show.
    ranked = sorted(
        products.items(),
        key=lambda item: (-sum(occurrences.get(item[0], [])), item[1]),
    )

    tier = max(len(ranked) // 3, 1)
    skus = []
    for rank, (class_id, name) in enumerate(ranked):
        seen = occurrences.get(class_id, [])
        skus.append(
            {
                # Sequential, NOT derived from class_id. The lookup that uses
                # this list is position-based — it never sees what the model
                # detected — so a code that encoded a class id would imply a
                # link to the detection beside it that does not exist.
                "code": f"SKU-{1001 + rank}",
                "name": name,
                # The name's own leading token. A grouping label, not a brand
                # database: this dataset ships no brand field.
                "brand": name.split()[0],
                "priority": min(rank // tier + 1, 3),
                "facings": max(round(statistics.mean(seen)), 1) if seen else 1,
            }
        )

    raw = yaml.safe_load(class_map_path.read_text())
    return {
        "source_dataset": str(raw["dataset"]),
        "dataset_version": str(raw["dataset_version"]),
        "generated_from": f"{artifact_dir.name}/class_map.yaml",
        "note": (
            "Demo stand-in for a planogram system. Generated by "
            "shelfeye_ml.artifact.export_planogram — do not hand-edit."
        ),
        "skus": skus,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("artifact_dir", nargs="?", type=Path, default=DEFAULT_ARTIFACT)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args()

    planogram = build(args.artifact_dir)
    args.output.write_text(json.dumps(planogram, ensure_ascii=False, indent=2) + "\n")
    print(f"wrote {len(planogram['skus'])} SKUs to {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
